[package]
name = "advent-of-code-2020"
version = "0.1.0"
authors = ["Konrad Borowski <konrad@borowski.pw>"]
edition = "2018"

[dependencies]
nom = "6.0.1"
num-complex = "0.3.1"
once_cell = "1.5.2"
structopt = "0.3.21"
